// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace WebApplication1 {
	
	
	public partial class _Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.ScriptManager sm;
		
		protected System.Web.UI.UpdatePanel UpdatePanel1;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl GLResultsChart;
		
		protected System.Web.UI.WebControls.GridView GLDeviceList;
		
		protected System.Web.UI.WebControls.CheckBox CheckBox1;
		
		protected System.Web.UI.WebControls.Button GLButton;
		
		protected System.Web.UI.UpdatePanel UpdatePanel2;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl FLOPResultsChart;
		
		protected System.Web.UI.WebControls.GridView FLOPDeviceList;
		
		protected System.Web.UI.WebControls.CheckBox CheckBox2;
		
		protected System.Web.UI.WebControls.Button FLOPSButton;
	}
}
