// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace PresentationDemo1
{
	public partial class MyController2 : UIViewController
	{
		public MyController2 (IntPtr handle) : base (handle)
		{
		}
	}
}
